name: RemoteMicIOS

options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.0"

targets:
  RemoteMicIOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
        excludes:
          - Info.plist
        buildPhase: resources
    settings:
      base:
        DEVELOPMENT_TEAM: L3QHLDRPAY
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.hd838a.RemoteMicIOS
        PRODUCT_NAME: RemoteMicIOS
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 10
        MARKETING_VERSION: 0.8.10
        TARGETED_DEVICE_FAMILY: "1,2"
  RemoteMicIOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: RemoteMicIOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.hd838a.RemoteMicIOSTests

schemes:
  RemoteMicIOS:
    build:
      targets:
        RemoteMicIOS: all
    run:
      config: Debug
    test:
      targets:
        - RemoteMicIOSTests
    archive:
      config: Release
